# -*- coding: utf-8 -*-
"""Hod Stock MARKET ANALYSIS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kKXFk7Y-HzcuXhD1mbzso0VBCfD4Sfos
"""

from google.colab import files
up=files.upload()

import io
import pandas as pd
data1=pd.read_csv(io.BytesIO(up["EOD-HD.csv"]))

data1.head()

data1.tail()

X=data1[["Open","High","Low","Volume"]].values
y=data1["Close"].values

# Commented out IPython magic to ensure Python compatibility.
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
# %matplotlib inline

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

lr=LinearRegression()
lr.fit(X_train,y_train)

y_pred=lr.predict(X_test)

print(lr.intercept_)

print(lr.coef_)

new_df=pd.DataFrame({"Actual":y_test.flatten(),"Predicted":y_pred.flatten()})

new_df.head(25)

print("Mean Square Error:",metrics.mean_squared_error(y_test,y_pred))

print("Mean Absolute Error:",metrics.mean_absolute_error(y_test,y_pred))

import math
print("Root Mean Square Error:",math.sqrt(metrics.mean_squared_error(y_test,y_pred)))

d=new_df.head(25)

d.plot(kind="bar")

