# -*- coding: utf-8 -*-
"""Untitled79.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KMOp9QsVSfCPFyVaDO9Yvymz52uW0ulQ
"""

from google.cloud import bigquery

# Set your GCP project ID
project_id = 'focus-copilot-406210'

# Create a BigQuery client
client = bigquery.Client(project=project_id)

# Define the BigQuery dataset and table
dataset_id = 'bigquery-public-data.eclipse_megamovie'
table_id = 'bigquery-public-data.eclipse_megamovie.astrometry_index_v_0_4'

# Get the table reference
table_ref = client.dataset(dataset_id).table(table_id)

# Get the table schema
table = client.get_table(table_ref)
schema = table.schema

# Display the schema
for field in schema:
    print(f"Field: {field.name}, Type: {field.field_type}, Mode: {field.mode}")
