# -*- coding: utf-8 -*-
"""Untitled79.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KMOp9QsVSfCPFyVaDO9Yvymz52uW0ulQ
"""

Str="Hello World"
print(Str)

